version: 0.0
os: linux
files:
  - source: scripts/
    destination: /var/www/html/scripts/actions
permissions:
  - object: /var/www/html/scripts/actions
    pattern: "*.sh"
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  AfterAllowTraffic: 
    - location: scripts/after_allow_traffic.sh
      timeout: 300

